### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by sje30** [mpas/hugo-multi-bootswatch#6]
Hi,

thanks for your work providing such a useful theme.

In the footer of each page, there is a broken link to "license".   the README.md mentions a page/license.md file - but that renders as ROOT/page/license/

Is there just a mismatch in the documentation?

Stephen

**Comment by reber0** [comment]
Home plate only shows the list of articles blog plate,
I want the home plate to show all the plates.
How should I do?
thank you.

**Comment by sje30** [comment]
Sorry, I'm not sure.  But its probably best to ask this as a separate issue.

I have a file content/home/index.md  to make the home page as mentioned on
https://discuss.gohugo.io/t/homepage-content-from-content-home-md/54/12

**Comment by sje30** [comment]
& fyi here is my page http://sje30.github.io
